# MongoDB

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-storage
              persistantVolumeClaim:
                claimName: mongodb-pvc

---
#mongodb persistant volume claim

apiVersion: v1
kind: PersistantVolumeClaim
metadata:
  name: mongodb-pvc
  labels: 
    app: fastapi-app
spec:
  replicas: 2
  selector: 
    matchlabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
        - name: fastapi-app
          image: fastapi-app:v1
          ports:
            - containerPort: 8000
          env:
            - name: MONGO-URI
              value: "mongodb://mongodb-service:27017"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

#FastApi service

apiversion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-app
  ports:
    - protocol: TCP
      port: 8000
      targetport: 8000
  type: ClusterIP


